# Generated by Django 2.2.5 on 2019-10-12 01:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='pago'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
