# Generated by Django 2.2.5 on 2019-11-15 00:14

from django.db import migrations, models
import django.db.models.deletion
import eventex.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191113_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(0, 'EMAIL'), (1, 'PHONE')], default=eventex.core.models.ContactTypes(0))),
                ('value', models.CharField(max_length=255)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Speaker')),
            ],
        ),
    ]
