# Generated by Django 2.2.5 on 2019-11-23 18:18

from django.db import migrations

"""
Steps:
- For any ABC, instantiate a MTI with all attributes
- Save MTI
- Associate the speakers from ABC to MTI
- Delete ABC
"""


def copy_src_to_dst(source, destination):
    for src in source.objects.all():
        dst = destination(
            title=src.title,
            start=src.start,
            description=src.description,
            slots=src.slots
        )
        dst.save()
        dst.speakers.set(src.speakers.all())
        src.delete()


def forward_course_to_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


def backward_course_to_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(
        apps.get_model('core', 'Course'),
        apps.get_model('core', 'CourseOld')
    )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_course'),
    ]

    operations = [
        migrations.RunPython(
            forward_course_to_abc_to_mti,
            backward_course_to_abc_to_mti
        )
    ]
